"""
Evidence - maps to the class diagram's Evidence entity.

`evidence_id` reuses the diagnostics engine's own Evidence.evidence_id
(a UUID, see diagnostics-engine/src/core/models.py) for the same reason
DiagnosisJob.job_id does - it's generated by the probe before this backend
ever sees it, and the AI reasoning layer references it by that same id
when validating findings (src/graph/nodes/evidence_agent.py in
ai-reasoning), so reusing it avoids an extra id-translation layer.

Addition beyond the diagram: `raw_data` (JSONB, nullable). The diagram's
`observedResult` is the human-readable normalized message; `raw_data`
additionally preserves the probe's full structured raw output
(diagnostics-engine Evidence.raw) for debugging/traceability. Optional -
never required by any endpoint.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.core.database import Base


class Evidence(Base):
    __tablename__ = "evidence"

    evidence_id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4()))
    job_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("diagnosis_jobs.job_id"), nullable=False)

    probe_type: Mapped[str] = mapped_column(String(32), nullable=False)      # e.g. CPU, MEMORY, HTTP
    observed_result: Mapped[str] = mapped_column(Text, nullable=False)       # raw/normalized result (probe message)
    result_status: Mapped[str] = mapped_column(String(16), nullable=False)   # e.g. OK, DEGRADED, FAILED
    latency_ms: Mapped[float | None] = mapped_column(Float, nullable=True)
    evidence_confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0)  # confidence in this evidence's reliability
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    raw_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # addition - full probe raw payload

    job: Mapped["DiagnosisJob"] = relationship(back_populates="evidence")
    hypothesis_links: Mapped[list["HypothesisEvidence"]] = relationship(back_populates="evidence", cascade="all, delete-orphan")

    def is_valid(self) -> bool:
        """An Evidence row is only meaningful if it's tied to a real job."""
        return self.job_id is not None

    def get_evidence_confidence(self) -> float:
        return self.evidence_confidence
