"""
Shared state for the InfraPilot LangGraph workflow.

The diagnostics-engine produces Evidence objects and publishes them
to Redis Streams. The Redis consumer converts those messages into
the evidence dictionaries stored in this state.

No LLM is used at this stage.
"""

from __future__ import annotations

from operator import add
from typing import Annotated, Any

from typing_extensions import TypedDict


class DiagnosisState(TypedDict, total=False):
    # ---------------------------------------------------------
    # Diagnosis identity
    # ---------------------------------------------------------

    job_id: str
    target: str

    # ---------------------------------------------------------
    # Raw evidence from diagnostics-engine
    # ---------------------------------------------------------

    evidence: list[dict[str, Any]]

    # ---------------------------------------------------------
    # Supervisor decision
    # ---------------------------------------------------------

    required_agents: list[str]

    # ---------------------------------------------------------
    # Findings generated by specialist agents
    #
    # These use reducers because Network/System/Application
    # agents can execute in parallel.
    # ---------------------------------------------------------

    network_findings: Annotated[
        list[dict[str, Any]],
        add,
    ]

    system_findings: Annotated[
        list[dict[str, Any]],
        add,
    ]

    application_findings: Annotated[
        list[dict[str, Any]],
        add,
    ]

    # ---------------------------------------------------------
    # Final evidence validation
    # ---------------------------------------------------------

    validated_findings: list[dict[str, Any]]

    # ---------------------------------------------------------
    # Final diagnosis
    # ---------------------------------------------------------

    root_cause: str
    confidence: float
    recommendations: list[str]

    # ---------------------------------------------------------
    # Errors
    # ---------------------------------------------------------

    errors: Annotated[
        list[str],
        add,
    ]